# Generated by Django 3.2.22 on 2023-11-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='book',
            new_name='product',
        ),
    ]
