# Generated by Django 3.2.22 on 2023-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_written',
            field=models.ManyToManyField(blank=True, related_name='books_written', to='babylon_books_app.Book'),
        ),
    ]
