# Generated by Django 3.2.22 on 2023-11-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0006_auto_20231115_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books_written',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_written', to='babylon_books_app.book'),
        ),
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
