# Generated by Django 3.2.22 on 2023-11-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0007_auto_20231115_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
