# Generated by Django 3.2.22 on 2023-11-25 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0008_auto_20231120_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
