# Generated by Django 3.2.22 on 2023-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0009_alter_book_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='placeholder_image', upload_to='images/'),
        ),
    ]
