# Generated by Django 3.2.22 on 2023-11-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0012_auto_20231127_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image_url',
        ),
        migrations.AddField(
            model_name='author',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='placeholder_image', upload_to='images/'),
        ),
    ]
