# Generated by Django 3.2.22 on 2023-11-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0013_auto_20231128_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
    ]
