# Generated by Django 3.2.22 on 2023-11-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0016_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
