# Generated by Django 3.2.22 on 2023-12-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0018_rename_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='body',
        ),
    ]
