# Generated by Django 3.2.22 on 2023-12-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0019_rename_text_review_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='text',
        ),
    ]
