# Generated by Django 3.2.22 on 2023-12-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0020_rename_body_review_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
