# Generated by Django 3.2.22 on 2023-12-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0022_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
