# Generated by Django 3.2.22 on 2023-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babylon_books_app', '0023_auto_20231203_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
